aa = input("Random number1")
bb = input("Random number1")
cc = input("Random number1")
dd = input("Random number1")
ee = input("Random number1")
ff = input("Random number1")
gg = input("Random number1")
hh = input("Random number1")
ii = input("Random number1")
jj = input("Random number1")

fin2 = open("nums3.txt","w")
fin2.write(aa + "\n" + bb + "\n" + cc + "\n" + dd + "\n" + ee + "\n" + ff + "\n" + gg + "\n" + hh + "\n" + ii + "\n" + jj)
fin2.close()